apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-copilot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: financial-copilot-frontend:latest
          ports:
            - containerPort: 8501
          env:
            - name: API_BASE_URL
              value: "http://financial-copilot-backend:8000"
